import {
  Dashboard,
  ConfirmationNumber,
  Add,
  People,
  Assessment,
  MenuBook,
  Inventory,
  Settings,
  Warning as IncidentIcon,
  Timer as SLAIcon,
  ChangeCircle,
  AdminPanelSettings,
  Security,
  BatchPrediction,
  Business,
  ShoppingCart as ServiceCatalogIcon,
  Support as CustomerPortalIcon,
  Psychology as ProblemIcon,
  Chat as CommunicationIcon,
  Link as IntegrationIcon,
  AutoFixHigh as AutomationIcon,
  Approval as ApprovalIcon,
  AccessTime as TimeTrackingIcon,
  SettingsApplications as SystemSettingsIcon,
} from '@mui/icons-material';

export const menuItems = [
  { text: 'Dashboard', icon: <Dashboard />, path: '/dashboard', roles: ['all'] },
  { text: 'Tickets', icon: <ConfirmationNumber />, path: '/tickets', roles: ['all'] },
  { text: 'Create Ticket', icon: <Add />, path: '/tickets/create', roles: ['all'] },
  {
    text: 'Incidents',
    icon: <IncidentIcon />,
    path: '/incidents',
    roles: ['IT Agent', 'Team Lead', 'IT Admin', 'Admin'],
  },
  {
    text: 'SLA Management',
    icon: <SLAIcon />,
    path: '/sla',
    roles: ['IT Admin', 'Admin'],
  },
  {
    text: 'Reports',
    icon: <Assessment />,
    path: '/reports',
    roles: ['Manager', 'IT Admin', 'Admin'],
  },
  { text: 'Knowledge Base', icon: <MenuBook />, path: '/knowledge-base', roles: ['all'] },
  {
    text: 'Change Management',
    icon: <ChangeCircle />,
    path: '/change-management',
    roles: ['IT Admin', 'Admin', 'Team Lead'],
  },
  {
    text: 'Problem Management',
    icon: <ProblemIcon />,
    path: '/problem-management',
    roles: ['IT Agent', 'Team Lead', 'IT Admin', 'Admin'],
  },
  {
    text: 'Service Catalog',
    icon: <ServiceCatalogIcon />,
    path: '/service-catalog',
    roles: ['IT Admin', 'Admin', 'Manager'],
  },
  {
    text: 'Customer Portal',
    icon: <CustomerPortalIcon />,
    path: '/customer-portal',
    roles: ['all'],
  },
  {
    text: 'Communication Hub',
    icon: <CommunicationIcon />,
    path: '/communication-hub',
    roles: ['IT Agent', 'Team Lead', 'IT Admin', 'Admin'],
  },
  {
    text: 'Asset Management',
    icon: <Inventory />,
    path: '/asset-management',
    roles: ['IT Admin', 'Admin', 'IT Agent'],
  },
  {
    text: 'Workflow Management',
    icon: <Settings />,
    path: '/workflow-management',
    roles: ['IT Admin', 'Admin'],
  },
  {
    text: 'User Management',
    icon: <People />,
    path: '/user-management',
    roles: ['IT Admin', 'Admin'],
  },
  {
    text: 'Integrations',
    icon: <IntegrationIcon />,
    path: '/integrations',
    roles: ['IT Admin', 'Admin'],
  },
  {
    text: 'Automation Rules',
    icon: <AutomationIcon />,
    path: '/automation-rules',
    roles: ['IT Admin', 'Admin'],
  },
  {
    text: 'Approvals',
    icon: <ApprovalIcon />,
    path: '/approvals',
    roles: ['Manager', 'Team Lead', 'IT Admin', 'Admin'],
  },
  {
    text: 'Time Tracking',
    icon: <TimeTrackingIcon />,
    path: '/time-tracking',
    roles: ['IT Agent', 'Team Lead', 'IT Admin', 'Admin'],
  },
  { text: 'Settings', icon: <Settings />, path: '/settings', roles: ['IT Admin', 'Admin'] },
];

export const adminMenuItems = [
  {
    text: 'Admin Dashboard',
    icon: <Business />,
    path: '/admin/dashboard',
    roles: ['IT Admin', 'Admin'],
  },
  {
    text: 'System Configuration',
    icon: <AdminPanelSettings />,
    path: '/admin/configuration',
    roles: ['IT Admin', 'Admin'],
  },
  {
    text: 'System Settings',
    icon: <SystemSettingsIcon />,
    path: '/system-settings',
    roles: ['IT Admin', 'Admin'],
  },
  {
    text: 'Bulk Operations',
    icon: <BatchPrediction />,
    path: '/admin/bulk-operations',
    roles: ['IT Admin', 'Admin'],
  },
  {
    text: 'Audit & Security',
    icon: <Security />,
    path: '/admin/audit-security',
    roles: ['IT Admin', 'Admin'],
  },
];
